// Minimal, dependency-free i18n. Default English (global launch); `auto` follows
// Obsidian's UI language. Keys are stable; untranslated keys fall back to English,
// then to the raw key — so a half-migrated UI degrades cleanly instead of breaking.

export type Lang = "en" | "pt";
export type LangPref = "auto" | Lang;

const en: Record<string, string> = {
  // commands
  "cmd.openOffice": "Open Agent Office",
  "cmd.answerMention": "Answer @mention on the current line",
  "cmd.generateCanvas": "Generate Canvas from the @mention on the current line",
  "cmd.runSquad": "Run squad (current note)",
  "cmd.actOnVault": "Act on vault (@mention)",
  "cmd.brainstorm": "Multi-agent brainstorm",
  "cmd.validateAgents": "Validate agents (frontmatter/structure)",
  "ribbon.openOffice": "Open Agent Office",
  // notices
  "notice.noAgentsInFolder": "No agents in the configured folder.",
  "notice.allValid": "✅ {count} agent(s) — all valid.",
  "notice.validateSummary": "{count} agent(s) · {errors} error(s) · {warns} warning(s).",
  "notice.validateMore": "\n… (rest in the console — Ctrl+Shift+I)",
  "notice.noProvider": "Configure an active provider in settings.",
  "notice.thinking": "{agent} is thinking…",
  "notice.openSquadNote": "Open the squad note and run the command on it.",
  "notice.noSteps": "No steps found. Use: 1. [[agent]]: instruction",
  "notice.agentNotFound": '"{ref}" agent (step {n}) not found.',
  "notice.squadCancelled": "Squad cancelled.",
  "notice.squadDone": '"{name}" squad finished — {count} steps.',
  "notice.needTwoAgents": "Create at least 2 agents for a brainstorm.",
  "notice.brainstormNoTurns": "Brainstorm produced no turns — try a faster provider (Groq/DeepSeek).",
  "notice.brainstormDone": '"{topic}" brainstorm {verb} — {count} turns.',
  "notice.verbStopped": "stopped",
  "notice.verbDone": "finished",
  "notice.agentReplied": "{agent} replied{via}.",
  "notice.via": " (via {name})",
  "notice.actedOnVault": "{agent} acted on the vault — {count} action(s).",
  "notice.noCanvasMap": "The agent didn't return a valid map — try again.",
  "notice.canvasGenerated": "Canvas generated by {agent}.",
  "notice.architectCreating": "Architect is creating the agent…",
  "notice.noAgentNote": "The AI didn't return a valid agent note — try again.",
  "notice.agentCreatedAI": "Agent created by AI: {name}",
  "notice.invalidName": "Invalid name.",
  "notice.agentExists": "An agent with that name already exists.",
  "notice.agentCreated": "Agent created: {name}",
  "notice.nothingToCrystallize": "Nothing to crystallize yet.",
  "notice.crystallized": "Crystallized: {path}",
  "mention.help": 'Write "@Agent: your question" in the note. Agents: {names}.',
  "mention.none": "(none — create one with + Agent)",
  // settings
  "set.language.name": "Language",
  "set.language.desc": "Interface language. Auto follows Obsidian's language.",
  "set.language.auto": "Auto",
};

const pt: Record<string, string> = {
  "cmd.openOffice": "Abrir Escritório de Agentes",
  "cmd.answerMention": "Responder @menção na linha atual",
  "cmd.generateCanvas": "Gerar Canvas da @menção na linha atual",
  "cmd.runSquad": "Rodar squad (nota atual)",
  "cmd.actOnVault": "Agir no cofre (@menção)",
  "cmd.brainstorm": "Brainstorm multi-agente",
  "cmd.validateAgents": "Validar agentes (frontmatter/estrutura)",
  "ribbon.openOffice": "Abrir Escritório de Agentes",
  "notice.noAgentsInFolder": "Nenhum agente na pasta configurada.",
  "notice.allValid": "✅ {count} agente(s) — tudo válido.",
  "notice.validateSummary": "{count} agente(s) · {errors} erro(s) · {warns} aviso(s).",
  "notice.validateMore": "\n… (resto no console — Ctrl+Shift+I)",
  "notice.noProvider": "Configure um provider ativo nas settings.",
  "notice.thinking": "{agent} está pensando…",
  "notice.openSquadNote": "Abra a nota do squad e rode o comando nela.",
  "notice.noSteps": "Nenhum passo encontrado. Use: 1. [[agente]]: instrução",
  "notice.agentNotFound": 'Agente "{ref}" (passo {n}) não encontrado.',
  "notice.squadCancelled": "Squad cancelado.",
  "notice.squadDone": 'Squad "{name}" concluído — {count} passos.',
  "notice.needTwoAgents": "Crie pelo menos 2 agentes para um brainstorm.",
  "notice.brainstormNoTurns": "Brainstorm sem falas — tente um provider mais rápido (Groq/DeepSeek).",
  "notice.brainstormDone": 'Brainstorm "{topic}" {verb} — {count} falas.',
  "notice.verbStopped": "parado",
  "notice.verbDone": "concluído",
  "notice.agentReplied": "{agent} respondeu{via}.",
  "notice.via": " (via {name})",
  "notice.actedOnVault": "{agent} agiu no cofre — {count} ação(ões).",
  "notice.noCanvasMap": "O agente não retornou um mapa válido — tente novamente.",
  "notice.canvasGenerated": "Canvas gerado por {agent}.",
  "notice.architectCreating": "Arquiteto criando o agente…",
  "notice.noAgentNote": "A IA não retornou uma nota de agente válida — tente de novo.",
  "notice.agentCreatedAI": "Agente criado pela IA: {name}",
  "notice.invalidName": "Nome inválido.",
  "notice.agentExists": "Já existe um agente com esse nome.",
  "notice.agentCreated": "Agente criado: {name}",
  "notice.nothingToCrystallize": "Nada para cristalizar ainda.",
  "notice.crystallized": "Cristalizado: {path}",
  "mention.help": 'Escreva "@Agente: sua pergunta" na nota. Agentes: {names}.',
  "mention.none": "(nenhum — crie em + Agente)",
  "set.language.name": "Idioma",
  "set.language.desc": "Idioma da interface. Auto segue o idioma do Obsidian.",
  "set.language.auto": "Auto",
};

const dicts: Record<Lang, Record<string, string>> = { en, pt };

let current: Lang = "en";

export function detectLang(): Lang {
  try {
    const l = (window.localStorage.getItem("language") || "").toLowerCase();
    return l.startsWith("pt") ? "pt" : "en";
  } catch {
    return "en";
  }
}

export function setLanguage(pref: LangPref): void {
  current = pref === "auto" ? detectLang() : pref;
}

export function getLanguage(): Lang {
  return current;
}

export function t(key: string, vars?: Record<string, string | number>): string {
  const d = dicts[current] || en;
  let s = d[key] ?? en[key] ?? key;
  if (vars) {
    for (const k of Object.keys(vars)) s = s.split(`{${k}}`).join(String(vars[k]));
  }
  return s;
}
